### ISSUE TITLE
Ubuntu 16.04 compability

### ISSUE THREAD

**Issue by koegs** [faf0/thinkpad-scripts#1]
Hi,

i recently got a Thinkpad X240 and installed (X)Ubuntu 16.04 on it. I also installed xserver-xorg-input-libinput so that i can use middle mouse scrolling with trackpoint, but now i cannot disable the touchpad without losing the trackpoint-"keys".

So do you think there is a way to make your script compatible to 16.04?

**Comment by faf0** [comment]
I made minor changes to `libinput-disable-touchpad-movements.sh` to make it compatible with Xubuntu 16.04. The script patches libinput to disable the touchpad, builds a package and installs it. Tested it on the X1 Carbon 2nd generation. In case you already have a `tmp-libinput` directory from a previous installation attempt, remove it and run `libinput-disable-touchpad-movements.sh` again. Let me know if the approach works for you.

**Comment by koegs** [comment]
Thx for the quick fix, unfortunately it doesn't work for me:

Reading package lists... Done
Building dependency tree  
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
libwacom-dev is already the newest version (0.18-1).
patch is already the newest version (2.7.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
**Picking 'libinput' as source package instead of 'libinput10'
E: Unable to find a source package for libinput**
./libinput-disable-touchpad-movements.sh: line 13: cd: libinput-1.?.?: No such file or directory
cp: cannot stat '../../evdev-mt-touchpad-disable-move.patch': No such file or directory
./libinput-disable-touchpad-movements.sh: line 15: debian/patches/series: No such file or directory
tail: cannot open 'debian/changelog' for reading: No such file or directory
dpkg-buildpackage: error: tail of debian/changelog gave error exit status 1
dpkg: error processing archive *.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 *.deb

**Comment by koegs** [comment]
Ok, first of all i should have activated the source-repos... then again on a fresh install you need to add some more packages:
dh-autoreconf debhelper fakeroot libmtdev-dev libudev-dev libevdev-dev

Now the script works and the compiled debs are installed on my test-VM, need to find a time to do this on my notebook. Will update you.

**Comment by faf0** [comment]
Thanks! I updated the script to install the mentioned dependencies and updated the README with further instructions.

**Comment by koegs** [comment]
Installed on my X240, Touchpad is disabled, Trackpoint-"Buttons" still work. Thanks!

**Comment by faf0** [comment]
Glad to hear that it also works on the X240! Closing the issue.

**Comment by ghost** [comment]
Hi, I have a problem about using touchpad of X240 too. I try excute libinput-disable-touchpad-movements.sh but It shows 
mkdir: cannot create directory ‘tmp-libinput’: File exists
Reading package lists... Done
Building dependency tree  
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
debhelper is already the newest version (9.20160115ubuntu3).
dh-autoreconf is already the newest version (11).
fakeroot is already the newest version (1.20.2-1ubuntu1).
libevdev-dev is already the newest version (1.4.6+dfsg-1).
libmtdev-dev is already the newest version (1.1.5-1ubuntu2).
libwacom-dev is already the newest version (0.18-1).
patch is already the newest version (2.7.5-1).
libudev-dev is already the newest version (229-4ubuntu7).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
./libinput-disable-touchpad-movements.sh: line 13: cd: libinput-1.?.?: No such file or directory
cp: cannot stat '../../evdev-mt-touchpad-disable-move.patch': No such file or directory
./libinput-disable-touchpad-movements.sh: line 15: debian/patches/series: No such file or directory
tail: cannot open 'debian/changelog' for reading: No such file or directory
dpkg-buildpackage: error: tail of debian/changelog gave error exit status 1
dpkg: error processing archive *.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 *.deb

I don't know what does it mean. Could help me to figure out this problem ?

Thank you so much.

**Comment by faf0** [comment]
Hi, the following line suggests that you do not have the source repositories activated in `/etc/apt/sources.list`:
`E: You must put some 'source' URIs in your sources.list`

To activate the source repositories, follow the instructions from, e.g., [here](https://help.ubuntu.com/community/Repositories/CommandLine) and [there](https://superuser.com/a/116737).

Please let me know, if that resolves your problem.
