### ISSUE TITLE
Re-enable touchpad movement

### ISSUE THREAD

**Issue by yblitum** [faf0/thinkpad-scripts#10]
The script to disable the touchscreen movement for Ubuntu 16.04 works perfect. After a few days, I wanted to re-enable it, but i did not manage to do it. Could you add a script, that reverses the disable script?

**Comment by faf0** [comment]
Hey, I'm glad the script works perfectly on your system. To re-enable the touchpad, you need to install the original libinput package. I cannot test it at the moment, but it might be as easy as `sudo apt-get install --reinstall libinput10`. Does that work? Please let me know and I can update the README accordingly.

**Comment by yblitum** [comment]
Yes, this worked perfectly. Thanks for the quick answer!
