### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by CillianMyles** [faf0/thinkpad-scripts#11]
I am currently experiencing touchpad not working issues on `Lenovo E560` fresh installing `18.04`.
Wondering if you think the `16.04` scripts should work on `18.04` or they need updates first?

Thank you,
Cillian

**Comment by faf0** [comment]
Hi @CillianMyles ! My guess is that the scripts are incompatible with `18.04`. I am not sure yet if I'll upgrade to `18.04`. Pull requests welcome!

**Comment by CillianMyles** [comment]
Okay just wanted to check. My issue has resolved itself I can only assume during an update! 
Thanks
